"""Lightweight DICOM processing primitives."""

from dicomforge.anonymize import (
    AnonymizationAction,
    AnonymizationEvent,
    AnonymizationPlan,
    AnonymizationReport,
    AuditEvent,
    AuditReport,
    PrivateTagAction,
    Rule,
    UidRemapper,
)
from dicomforge.api import (
    DicomFile,
    batch_anonymize,
    quick_anonymize,
    validate_dataset,
    validate_for_sop_class,
)
from dicomforge.codecs import (
    Codec,
    CodecRegistry,
    pydicom_pixel_codec,
    pydicom_pixel_registry,
)
from dicomforge.charset import (
    DEFAULT_CHARACTER_SET,
    PersonName,
    can_encode_text,
    coerce_person_name,
    dataset_character_set,
    decode_text,
    encode_text,
    ensure_text_encodable,
    normalize_specific_character_set,
    preferred_specific_character_set,
    python_codecs_for_character_set,
)
from dicomforge.dataset import DicomDataset
from dicomforge.dicomweb import (
    DicomwebClient,
    DicomwebError,
    DicomwebResponse,
    DicomwebTransport,
    MultipartPart,
    QidoQuery,
    UrllibDicomwebTransport,
    build_multipart_related,
    build_multipart_related_streaming,
    dataset_from_dicom_json,
    dataset_to_dicom_json,
    datasets_from_dicom_json,
    parse_multipart_related,
    parse_multipart_related_streaming,
)
from dicomforge.errors import (
    CharacterSetError,
    DicomForgeError,
    DicomValidationError,
    InvalidTagError,
    MissingBackendError,
    UnsupportedTransferSyntaxError,
)
from dicomforge.transport import (
    BearerTokenTransport,
    RequestsDicomwebTransport,
    RetryTransport,
    StreamingDicomwebResponse,
)
from dicomforge.network import (
    Association,
    AssociationClosedError,
    AssociationRejectedError,
    AssociationRequest,
    DimseServer,
    DimseStatus,
    NetworkError,
    open_association,
    start_dimse_server,
)
from dicomforge.pixels import (
    FrameMetadata,
    PixelCapability,
    PixelMetadataError,
    VoiLut,
    apply_voi_window,
    apply_voi_window_from_dataset,
    assert_pixel_data_length,
    check_pixel_capability,
    expected_samples_per_pixel,
    is_monochrome,
    needs_inversion,
    normalize_photometric_interpretation,
    rescale_from_dataset,
    rescale_value,
    rescale_values,
    voi_window_bounds,
)
from dicomforge.tags import Tag
from dicomforge.transfer_syntax import TransferSyntax
from dicomforge.uids import (
    DimseStatusCode,
    ImplementationUID,
    SopClassUID,
    TransferSyntaxUID,
    generate_uid,
    is_valid_uid,
)

__all__ = [
    # Anonymization
    "AnonymizationAction",
    "AnonymizationEvent",
    "AnonymizationPlan",
    "AnonymizationReport",
    "AuditEvent",
    "AuditReport",
    "PrivateTagAction",
    "Rule",
    "UidRemapper",
    # High-level API
    "DicomFile",
    "batch_anonymize",
    "quick_anonymize",
    "validate_dataset",
    "validate_for_sop_class",
    # Codecs
    "Codec",
    "CodecRegistry",
    "pydicom_pixel_codec",
    "pydicom_pixel_registry",
    # Character sets
    "DEFAULT_CHARACTER_SET",
    "PersonName",
    "can_encode_text",
    "coerce_person_name",
    "dataset_character_set",
    "decode_text",
    "encode_text",
    "ensure_text_encodable",
    "normalize_specific_character_set",
    "preferred_specific_character_set",
    "python_codecs_for_character_set",
    # Core types
    "DicomDataset",
    "Tag",
    "TransferSyntax",
    # Errors
    "CharacterSetError",
    "DicomForgeError",
    "DicomValidationError",
    "InvalidTagError",
    "MissingBackendError",
    "NetworkError",
    "PixelMetadataError",
    "UnsupportedTransferSyntaxError",
    # DICOMweb
    "DicomwebClient",
    "DicomwebError",
    "DicomwebResponse",
    "DicomwebTransport",
    "MultipartPart",
    "QidoQuery",
    "UrllibDicomwebTransport",
    "build_multipart_related",
    "build_multipart_related_streaming",
    "dataset_from_dicom_json",
    "dataset_to_dicom_json",
    "datasets_from_dicom_json",
    "parse_multipart_related",
    "parse_multipart_related_streaming",
    # Transport (0.7)
    "BearerTokenTransport",
    "RequestsDicomwebTransport",
    "RetryTransport",
    "StreamingDicomwebResponse",
    # Networking
    "Association",
    "AssociationClosedError",
    "AssociationRejectedError",
    "AssociationRequest",
    "DimseServer",
    "DimseStatus",
    "DimseStatusCode",
    "open_association",
    "start_dimse_server",
    # Pixels
    "FrameMetadata",
    "PixelCapability",
    "VoiLut",
    "apply_voi_window",
    "apply_voi_window_from_dataset",
    "assert_pixel_data_length",
    "check_pixel_capability",
    "expected_samples_per_pixel",
    "is_monochrome",
    "needs_inversion",
    "normalize_photometric_interpretation",
    "rescale_from_dataset",
    "rescale_value",
    "rescale_values",
    "voi_window_bounds",
    # UIDs
    "ImplementationUID",
    "SopClassUID",
    "TransferSyntaxUID",
    "generate_uid",
    "is_valid_uid",
]
